version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: crush_tracker_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: crush_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Host:Container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
